### ISSUE TITLE
Release todo 17.1.0-rc.2

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10294]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [ ] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [ ] Check all milestones don't have priority issues still open
    - [ ] https://github.com/nextcloud/spreed/milestone/205
- [ ] On first beta of a major release
    - [ ] Create `New in Talk 17.1` entries in the `Talk updates ✅` conversation https://github.com/nextcloud/spreed/pull/10173
    - [ ] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [ ] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch
- [ ] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [ ] 
- [ ] Merge the PR

## 🚀 v17.1.0-rc.2
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
  
   
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable27
    git pull origin stable27
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v17.1.0-rc.2` will be automatically added to the tag)
    ```sh
    make create-tag version=17.1.0-rc.2
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v17.1.0-rc.2
    ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v17.1.0-rc.2
    - [ ] Add the respective `CHANGELOG.md` section
    - [ ] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v17.1.0-rc.2
    - [ ] Copy the release description from before
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `💚 Next Patch (27)` to `v17.1.0-rc.2` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💚 Next Patch (27)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v17.1.0-rc.2` to `💚 Next Patch (27)`
- [ ] Close the `v17.1.0-rc.2` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
