### ISSUE TITLE
🚀 Release todo 16.0.8, 17.1.3 and 18.0.0-rc.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#10946]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/218
    - [x] https://github.com/nextcloud/spreed/milestone/214
    - [x] https://github.com/nextcloud/spreed/milestone/213
- [x] On first RC of a major release
    - [x] Create `New in Talk 18` entries in the `Talk updates ✅` conversation
      - https://github.com/nextcloud/spreed/pull/10945
    - [ ] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [x] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [x] https://github.com/nextcloud/spreed/pull/10987
- [ ] Merge the PR

## 🚀 v16.0.8
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/10988
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
  
   
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable26
    git pull origin stable26
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v16.0.8` will be automatically added to the tag)
    ```sh
    make create-tag version=16.0.8
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v16.0.8
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v16.0.8
    - [x] Add the respective `CHANGELOG.md` section
    - [x] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v16.0.8
    - [x] Copy the release description from before
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `🧡 Next Patch (26)` to `v16.0.8` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `🧡 Next Patch (26)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v16.0.8` to `🧡 Next Patch (26)`
- [x] Close the `v16.0.8` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team

## 🚀 v17.1.3
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/10989
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
  
   
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable27
    git pull origin stable27
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v17.1.3` will be automatically added to the tag)
    ```sh
    make create-tag version=17.1.3
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v17.1.3
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v17.1.3
    - [x] Add the respective `CHANGELOG.md` section
    - [x] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v17.1.3
    - [x] Copy the release description from before
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (27)` to `v17.1.3` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (27)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v17.1.3` to `💚 Next Patch (27)`
- [x] Close the `v17.1.3` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team

## 🚀 v18.0.0-rc.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/10990
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
  
   
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout main
    git pull origin main
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v18.0.0-rc.1` will be automatically added to the tag)
    ```sh
    make create-tag version=18.0.0-rc.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v18.0.0-rc.1
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v18.0.0-rc.1
    - [x] Add the respective `CHANGELOG.md` section
    - [x] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v18.0.0-rc.1
    - [x] Copy the release description from before
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💙 Next Beta (28)` to `v18.0.0-rc.1` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💙 Next Beta (28)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v18.0.0-rc.1` to `💙 Next Beta (28)`
- [x] Close the `v18.0.0-rc.1` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
