### ISSUE TITLE
✏️ Edit message - API

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11206]
- See overview at https://github.com/nextcloud/spreed/issues/11203

---

* PR and todo at https://github.com/nextcloud/spreed/pull/11207

---

### 🚧 Tasks

- [x] System message hidden like with delete
    - https://github.com/nextcloud/spreed/pull/11207
- [ ] Make sure editing of captions for shared files work as well
    - [ ] Don't allow changing from message to caption and vice-versa
- [ ] Visible indicator a message was edited (and by whom/when)
    - [x] Amend to the author name ` (edited)` / ` (edited by moderator-name)`
        - https://github.com/nextcloud/spreed/pull/11207
    - [x] Editor+Time in Message menu as subline of timestamp
        - https://github.com/nextcloud/spreed/pull/11207
    - [ ] Displayname is hardcoded to id
- [ ] Time limitation like for delete?
    - [x] Limit editing to X hours (draft 24 hours, check what others do and discuss again)
        - https://github.com/nextcloud/spreed/pull/11207
    - [ ] Set the limit on deletion to infinite
- [ ] What to do about mention notifications (added a mention, removed a mention)
    - [ ] Should diff mentions and add/remove notifications accordingly
    - [ ] Make sure people don't get 1 for the message and 2 for followup edits
- [ ] What about bots?
    - [x] Can not edit bot messages, moderators can
    - If a message triggered a bot already it's yolo and will not be retriggered with the new content automatically (bot can do based on the system message?)
        -  [ ] Return 202 (also on delete) like with matterbridge
            - https://github.com/nextcloud/spreed/pull/11367
- [ ] 🔖 Capability is added
- [ ] Prevent editing to empty string
