### ISSUE TITLE
🌐 Federated chatting 💬 - API

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11272]
- Overview ticket at https://github.com/nextcloud/spreed/issues/11231

---

- [ ] Provide correct relative user objects in chat messages:
  - `user_a` from `server_1` invites `user_b` from `server_2` to the room
  - When `user_b` request data from `server_1`, it uses credentials like userId: `user_b@server_2`
  - Messages should show user_a as `user_a@server_1` and user_b as `user_b` / `you`
  - System message text should reflect as `{federated_user} invited {user} / you` instead of `{user / actor} invited {federated_user}` 
- [ ] Conversation parameters, as `unreadMessages`, should be aligned with federated users
- [ ] Message parameters, as `isReplyable`, should consider federated users
https://github.com/nextcloud/spreed/blob/54c2802c56d5d5ab6c8729667ce5aadf3d19c9cb/lib/Model/Message.php#L176

### 🚧 Tasks

**Legend:**
- 🟥 Must have
- 🟨 Should have
- 🟩 Good to have
- ⚫ Not for now

---

- [x] Avatar
    - [x] getAvatar 🟨 #11587
    - [x] getAvatarDark 🟨 #11587
    - [x] ~~uploadAvatar~~ ⚫ Moderation is not supported in TalkV1
    - [x] ~~emojiAvatar~~ ⚫ Moderation is not supported in TalkV1
    - [x] ~~deleteAvatar~~ ⚫ Moderation is not supported in TalkV1
- [ ] Chat
    - [x] receiveMessages 🟥 #11587
    - [x] sendMessage 🟥 #11587
    - [x] deleteMessage 🟥 #11587
    - [x] editMessage 🟥 #11587
    - [x] getMessageContext 🟥 #11587
    - [x] setReadMarker 🟥 #11674
    - [ ] setReminder 🟨 
    - [ ] getReminder 🟨 
    - [ ] deleteReminder 🟨 
    - [x] markUnread 🟨 #11674
    - [x] mentions 🟨  #11587
    - [ ] ~~shareObjectToChat~~ ⚫
    - [ ] ~~getObjectsSharedInRoomOverview~~ ⚫
    - [ ] ~~getObjectsSharedInRoom~~ ⚫
    - [x] ~~clearHistory~~ ⚫ Moderation is not supported in TalkV1
- [ ] Room
    - [x] getParticipants 🟥 #11587
    - [x] 🆕 capabilities 🟥 #11587
    - [x] favorite 🟥 https://github.com/nextcloud/spreed/pull/11743
    - [x] notifications 🟥 https://github.com/nextcloud/spreed/pull/11743
    - [x] join "room" (available for chatting) 🟥
    - [ ] leave "room" (not available for chatting anymore) 🟥
    - [x] remove self from conversation 🟥 https://github.com/nextcloud/spreed/pull/11747
    - [ ] setSessionState 🟥
    - [ ] …
- [x] Reaction 🟥 
- [x] Polls 🟨
