### ISSUE TITLE
`@nextcloud/vue`: library bump follow-ups

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#11494]
9.0.x -  Vue3:

The package has dropped compatibility with Nextcloud before version 32.
This mostly affects the visual appearance of components.
NcButton now does no longer has role="button" when used as a link (passing the href prop or a router link (to)).
Instead, for accessibility and semantical correctness, has the link role.
NcColorPicker
The deprecated close event was removed in favor of the closed event, this was done for consistent event names.
NcColorPicker
The update:open event is removed in favor of the already available close event.
NcTextField:
The value 'arrowRight' for the trailingButtonIcon property was deprecated is now removed in favor of arrowEnd.

NcColorPicker
The update:open event was undeprecated, instead proper open state handling of the component was added.
This means it is now possible to pass the open prop directly to the component,
it is implemented as two-way binding with the corresponding update:open event.
It is now discouraged to use the previous solution of relying on the shown prop of the underlying component.

Additionally for consistent event naming the close event was deprecated in favor of the closed event.
The closed event will be emitted after update:open (with payload false) was emitted and all transitions have finished.

- [ ] feat(NcThemeProvider): allow to override the current theme for parts of the UI 
- [ ] feat(NcColorPicker): add proper open-state handling
- [x] feat: add visual border for buttons on Nextcloud 32+
- [x] feat(NcUserStatusIcon): update status icons
- [ ] feat(NcHeaderMenu): apply alpha mask to icon slot (notifications, usermenu bug)
- [ ] fix: migrate from _oc_config to initial state
- [x] fix: auto-resolve focus trap stack, if was changed outside of controller
- [ ] refactor: use secondary colors for buttons on Nextcloud 32+
- [ ] feat: add useFormatRelativeTime composable
- [ ] feat(NcPasswordField): allow to set visibility state
- [x] refactor: deprecate events not comply with Vue event naming rules `'interact-todo'`
- [x] chore(NcColorPicker): deprecate duplicated update:open event
- [x] feat(NcChip): allow to define the actions container
- [x] feat(NcActionButton): introduce description prop

---

8.26.1+ (same in Vue 3)

8.26.0 - https://github.com/nextcloud/spreed/pull/14939
- [ ] feat(NcAppSidebar): add `info` slot - sidebar rework
- [x] feat(NcPopover): add new `noFocusTrap` prop - migrate
- [x] fix(NcMentionBubble): position selectable text aligned with the component - scroll fix
- [x] fix(NcAvatar): do not load avatar from server, if iconClass was provided - avatar fix
- [ ] fix(NcSelectUsers): add missing `search` event  - check if can migrate

8.25.1 - https://github.com/nextcloud/spreed/pull/14887
- [ ] feat(NcDateTimePicker): double-check props
- [x] feat: provide `NcSelectUsers` - double-check
- [x] add `directional` prop to NcIconSvgWrapper
- [x] fix(NcRichContenteditable): add correct tooltip
- [ ] fix(NcRichContenteditable): bring back error style on overflow - set maxlength?
- [x] fix(NcAvatar): skip user status request if `hideStatus` prop was provided
- [x] deprecate `Tooltip` directive for accessibility

8.24.0 - https://github.com/nextcloud/spreed/pull/14778
- [x] feat: add boolean prop alternatives with false as default value
- [x] fix: lock mdast-util dependency for Safari 16.4
- [x] `NcButton` | `NcDialogButton` `variant` and `native-type` props - migrate, eslint rule
- [ ] feat(NcActions): add `opened` and `closed` events to handle closing/opening end
- [ ] feat(NcBlurHash): Add a blur hash component
- [ ] feat(NcDialog): Allow to catch `reset` event
- [ ] feat(NcAppContent): Allow to set the page title
- [ ] fix(NcPopover): correctly wait for animation end in `after-show`/`after-hide` events
- [ ] fix(NcEmojiPicker): not focusable when used in another focus trap
- [ ] fix(NcAppSidebar, NcHeaderMenu): correctly focus trigger/close button when no focusable elements inside
- [ ] fix(NcInputField): Only show error state border if user interacted with the input
- [ ] fix(NcEmojiPicker): return focus steals actual focus

<details>

<summary>History and solved tasks</summary>

8.23.1 - https://github.com/nextcloud/spreed/pull/14385
- [x] feat: Allow to import without `dist` - migrate, eslint rule
- [x] feat(Nc*Field): add `#icon` slot - NcTextField in 3 places
- [x] fix(NcActionRadio): change `modelValue`
- [x] fix(NcDateTimePicker): selected and hover time is not readable
- [x] fix(NcDateTimePickerNative): do not set invalid value on clear event - SearchMessageTab comment
- [x] fix(NcDateTimePickerNative): style alignment with other input components - remove overwrites

8.22.0 - https://github.com/nextcloud/spreed/pull/14052
- [x] feat(NcAppNavigation): add `n` hotkey to toggle navigation
- [x] style(NcCheckboxRadioSwitch): fix styles in disabled state 
- [x] fix(NcModal): make 'Close' button the last element for the focus-trap
- [x] fix(NcDateTimePicker): popup position
- [x] fix(useHotKey): allow hotkeys with implicit `SHIFT` and add `caseSensitive`, custom event filter options
- [x] fix(NcRichContenteditable): prevent content from overflowing https://github.com/nextcloud/spreed/pull/14059

8.21.0 - https://github.com/nextcloud/spreed/pull/13840
- [x] feat(NcRichText): highlight code syntax if language provided
- [x] fix(NcRichContenteditable): do not break adjacent user mentions
- [x] fix(NcRichContenteditable): fix pasting of the content to an empty field

8.20.0 - https://github.com/nextcloud/spreed/pull/13755
- [x] feat: add `v-model` support - https://github.com/nextcloud/spreed/pull/14046
- [x] feat: forward compatibility with v9 on `v-model` props/events
- [x] feat(NcRichText): make interactive widgets opt-in - https://github.com/nextcloud/spreed/pull/13573
- [x] feat: add `isDarkTheme` functions and composables - https://github.com/nextcloud/spreed/pull/13795

8.19.0 - https://github.com/nextcloud/spreed/pull/13326
- [x] fix(NcAvatar): add a fallback for missing CSS variable
- [x] style(NcColorPicker): adjust styles of advanced fields to match NcInputField

8.18.0 - https://github.com/nextcloud/spreed/pull/13284
- [x] fix(NcCheckboxRadioSwitch): switch may have incorrect checked-like background 
- [x] fix(NcEmojiPicker): adjust hover effects to the new design 

8.17.1 - https://github.com/nextcloud/spreed/pull/13190
- [x] fix(NcRichText): discard reference widgets on text update 
- [x] fix(NcCheckBoxRadioSwitch): do not toggle on a click on a link inside 
- [x] fix(useHotKey): respect press of MacOS Cmd key as Ctrl key 

8.17.0 - https://github.com/nextcloud/spreed/pull/13068
- [x] feat(NcDialog): Allow to make the dialog a form - check if needed
- [x] feat(NcListItem): allow to control the display of a three dot menu - change #13074
- [x] feat(NcCounterBubble): add count prop for humanized count display - add #13074
- [x] feat(useHotKey): add composable for keyboard shortcuts - refactor old PR
- [x] fix(NcAvatar): extend variable size of status icons - wait for adjustment in next release, then cleanup styles

8.16.0 - https://github.com/nextcloud/spreed/pull/12900
- [x] feat(NcPasswordField): Add as-text prop to remove autocomplete #13074
- [x] fix(NcNoteCard): Adjust padding and margin - clean up styles #13074
- [x] feat(NcNoteCard): Add text prop to pass the content of the note card - use it #13074

8.15.0 - https://github.com/nextcloud/spreed/pull/12767
- [x] feat(NcAppNavigation): Provide consistent in-app search - use template#search
- [x] fix(NcInputField): Make focus visible on trailing button look better - similar buttons

8.14.0 - https://github.com/nextcloud/spreed/pull/12643
- [x] feat: migrate NcCollectionList component from nextcloud-vue-collections https://github.com/nextcloud/spreed/pull/12643
- [x] fix(NcDialog, NcModal): Ensure the dialog is correctly labelled by its name

8.13.0 - https://github.com/nextcloud/spreed/pull/12387
- [x] feat(NcRichContenteditable): programmatically show tributes https://github.com/nextcloud/spreed/issues/12250
- [x] fix(richText): do not handle relative links without leading slash as router links
8.12.0
- [x] feat(NcAppSidebar): Allow to set open state to prevent focus trap issues on mobile https://github.com/nextcloud/spreed/pull/12387

8.11.3 - https://github.com/nextcloud/spreed/pull/12298
- [x] check that error is gone: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5485
- [x] fix(NcColorPicker): Choose button, add HEX choose
- [x] fix(autolink): check with desktop client
- [x] fix(NcEmojiPicker): https://github.com/nextcloud/spreed/pull/12285 

8.11.2 - https://github.com/nextcloud/spreed/pull/12048
- [x] NcRichText - missing mentions, sublists
- [x] Vue Router - adjusted for Talk Desktop

8.11.1 - https://github.com/nextcloud/spreed/pull/11887
- [x] avatars in dark mode
- [x] NcListItem - font-weight to 500

8.11.0 - https://github.com/nextcloud/spreed/pull/11818

8.10.0 - https://github.com/nextcloud/spreed/pull/11774
- [x] NcReferenceWidget - opt out for sidebars
- [x] NcListItem - make bold again - in 8.11
- [x] NcRichcontenteditable - autocomplete behaviour

8.9.1 - https://github.com/nextcloud/spreed/pull/11748
8.9.0

8.8.1 - https://github.com/nextcloud/spreed/pull/11681
8.8.0
- [x] NcActions - check keyboard navigation
- [x] NcRichcontenteditable - user mentions

8.7.1 - https://github.com/nextcloud/spreed/pull/11625
- [x] Reference widget - broken, fixed in 8.8.0

8.7.0 - https://github.com/nextcloud/spreed/pull/11608
- [x] NcModal - remove TODO styles `:deep(.modal-wrapper--small .modal-container)`
- [x] check NcListItem styles - https://github.com/nextcloud/spreed/issues/11601

8.6.2 - https://github.com/nextcloud/spreed/pull/11569
- [x] NcRichContenteditable - remove patch for autocomplete from NewMessage
- [x] NcRichContenteditable - fix broken tribute

8.6.1 - https://github.com/nextcloud/spreed/pull/11521

8.6.0 - https://github.com/nextcloud/spreed/pull/11492
- [x] NcNoteCard: use custom icon slot for `NewMessageAbsenceInfo` #11545
- [x] NcListItem: details slot for Conversation

8.5.1 - https://github.com/nextcloud/spreed/pull/11490
8.5.0
- [x] NcSelect: Add visible input label - align grid in Admin settings
- [x] NcInputField: emit numeric - migrate BreakoutRoomsEditor TextField to NcInputField
- [x] NcProgressBar: circular progress bar - consider for FilePreview upload
- [x] NcActionButton: pressed state - SearchBox filter buttons #11614
- [x] NcRichText: support of GFM - enable extended markdown
- [x] NcRichText: add interactive checkboxes #11402

</details>

**Comment by nickvergessen** [comment]
All buttons are misaligned in a call

![grafik](https://github.com/nextcloud/spreed/assets/213943/bc4a7976-784c-4a06-98db-260d6a5eece8)

**Comment by Antreesy** [comment]
Plus a copy-paste from design review:

## Talk

* [ ] Search field 
  - [ ] text moves on hover
  - [ ] can be not rounded
  - [ ] spacing on left should be adjusted
* [ ] Settings page
  - [ ] "Choose folder..." should be `<p>` and not h3
  - [ ] section headings on left shouldn't be pill
  - [ ] Attachments folder input field misaligned
* [ ] Filter action menu items have extra spacing on right
* [ ] Settings item in conversation list has too much border radius
* [ ] List item in conversation list
  - [ ] Spacing on the left too much
  - [ ] Avatar circle is slightly cut off
  - [ ] Avatar circle should have transparant bg + same bg on hover
* [ ] Join open conversations dialog
  - [ ] heading waaay too big
* [ ] Create new conversation
  - [ ] same heading size issue
  - [ ] Use JS autosize for description so it auto resizes 
* [ ] Start call button should have spacing on the right
* [ ] main message input field
  - [ ] height is broken
  - [ ] emoji doesn't have hover feedback
* [ ] Conversation icon is too big
* [ ] Conversation title + subline is cut off
* [ ] When you hover on a message, the reaction/reply/more bubble items should be rounded
* [ ] In the 3 dot menu of a message
  - [ ] if the menu extends message area it is cut off 
  - [ ] "Set reminder" size is off

**Comment by nickvergessen** [comment]
\-- 15. Talk: Text size and alignment broken. /Talk in input line not aligned.
\-- 16. Talk: Edit button for name and description to far away and disconnected from the labels.
\-- 17. Talk: The ‘share’ (and federation) icon should stay inside the blue highlighted area.

**Comment by Antreesy** [comment]
We can switch to NcActionRadio in Notifications, but I don't like how it looks:
B | A
-- | --
![Image](https://github.com/user-attachments/assets/bf85f9d2-ff40-4dfa-8215-38d9048c7005) | ![Image](https://github.com/user-attachments/assets/494395d8-ec2d-4ebe-80af-ce3dad287131)

**Comment by nickvergessen** [comment]
> We can switch to NcActionRadio in Notifications, but I don't like how it looks:

If we do this, the call notification should also turn into a switch or checkbox.
But I really miss the explaining icons
