### ISSUE TITLE
⛵ Release todo 19.0.0-beta.5

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#11924]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [ ] Check all milestones don't have priority issues still open
    - [ ] https://github.com/nextcloud/spreed/milestone/239

## 🚀 v19.0.0-beta.5
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [ ] https://github.com/nextcloud/spreed/pull/11884
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
  
   
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout main
    git pull origin main
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v19.0.0-beta.5` will be automatically added to the tag)
    ```sh
    make create-tag version=19.0.0-beta.5
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v19.0.0-beta.5
    ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v19.0.0-beta.5
    - [ ] Add the respective `CHANGELOG.md` section
    - [ ] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v19.0.0-beta.5
    - [ ] Copy the release description from before
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `💞 Next Beta (29)` to `v19.0.0-beta.5` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💞 Next Beta (29)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v19.0.0-beta.5` to `💞 Next Beta (29)`
- [ ] Close the `v19.0.0-beta.5` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
