### ISSUE TITLE
🍧 Conversation creation - Overview

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#12294]
## Overview

- At the moment the differences are quite big between the iOS and Android app and even bigger against the web frontend.
- While it is okay that there is a difference, the flow should be similar enough, so that a experienced user from 1 platform can easily showcase/explain it to a user of the other platforms
- There is also the request to make it more "obvious" how a 1-1 conversation can be created

## Todo

- [ ] Make a design meeting with the design team and representatives from:
  - [ ] Web: @Antreesy (picked for coordination, feel free to reassign to another dev of the area)
  - [x] iOS: @Ivansss (picked for coordination, feel free to reassign to another dev of the area)
  - [ ] Android: @mahibi (picked for coordination, feel free to reassign to another dev of the area)
- [ ] Protocol the meeting out come in this ticket here
- [ ] Raise issues in the respective repositories to follow up with the needed todos

## Refs
- https://github.com/nextcloud/talk-android/issues/3794

**Comment by Ivansss** [comment]
Here you can find the new iOS views for creating a new conversation or joining an open conversation. @sowjanyakch 

| Conversation list | 1. Create a new conversation <br> 2. Join open conversation <br> 3. Create one2one conversation  | Create a new conversation  |
|---|---|---|
| ![IMG_E0049](https://github.com/nextcloud/talk-ios/assets/4638605/06cd0f0a-25b7-4dd5-8e1a-8513886470d4) | ![IMG_E0046](https://github.com/nextcloud/talk-ios/assets/4638605/8931126e-62dd-40bb-bf2a-2a88d4e267eb) | ![IMG_E0048](https://github.com/nextcloud/talk-ios/assets/4638605/be55f813-3fb6-4a65-9d83-b7fb67a86e5d) |
