### ISSUE TITLE
Release todo 17.1.9, 18.0.8 and 19.0.1

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#12405]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/250
    - [x] https://github.com/nextcloud/spreed/milestone/248
    - [x] https://github.com/nextcloud/spreed/milestone/247
- [x] On first RC of a major release
    - [ ] Create `New in Talk TX` entries in the `Talk updates ✅` conversation
    - [ ] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [ ] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [x] https://github.com/nextcloud/spreed/pull/12406
- [x] Merge the PR

## 🚀 v19.0.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/12409
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stableX.Y
    git pull origin stableX.Y
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `vX.Y.Z` will be automatically added to the tag)
    ```sh
    make create-tag version=X.Y.Z
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [x] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=vX.Y.Z
    - [x] Make sure that chosen tag is vX.Y.Z, target is stableX.Y, and previous tag is vX.Y.[Z-1]
    - [x] Add the respective `CHANGELOG.md` section from merged PR
    - [x] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=vX.Y.Z
    - [x] Copy the full content from the release description of the previous step
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (X)` to `vX.Y.Z` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [x] Close the `vX.Y.Z` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
- [x] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)

## 🚀 v18.0.8
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/12408
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stableX.Y
    git pull origin stableX.Y
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `vX.Y.Z` will be automatically added to the tag)
    ```sh
    make create-tag version=X.Y.Z
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [x] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=vX.Y.Z
    - [x] Make sure that chosen tag is vX.Y.Z, target is stableX.Y, and previous tag is vX.Y.[Z-1]
    - [x] Add the respective `CHANGELOG.md` section from merged PR
    - [x] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=vX.Y.Z
    - [x] Copy the full content from the release description of the previous step
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (X)` to `vX.Y.Z` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [x] Close the `vX.Y.Z` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
- [x] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)

## 🚀 v17.1.9
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/12407
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stableX.Y
    git pull origin stableX.Y
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `vX.Y.Z` will be automatically added to the tag)
    ```sh
    make create-tag version=X.Y.Z
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [x] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=vX.Y.Z
    - [x] Make sure that chosen tag is vX.Y.Z, target is stableX.Y, and previous tag is vX.Y.[Z-1]
    - [x] Add the respective `CHANGELOG.md` section from merged PR
    - [x] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=vX.Y.Z
    - [x] Copy the full content from the release description of the previous step
    - [x] Set as a (pre-)release
    - [x] Publish release
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (X)` to `vX.Y.Z` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [x] Close the `vX.Y.Z` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
- [x] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)
