### ISSUE TITLE
🚀 Release todo 20.0.0-beta.1

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#12820]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/240
- [x] Check there are no important PRs open against the branch
    - [x] https://github.com/nextcloud/spreed/pulls?q=is%3Apr+is%3Aopen+base%3Amain

## 🚀 v20.0.0-beta.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
   
    - [x] https://github.com/nextcloud/spreed/pull/12822
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [x] Merge the PR
- [x] Make sure you pull the latest main branch:
    ```sh
    git checkout main
    git pull origin main
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v20.0.0-beta.1` will be automatically added to the tag)
    ```sh
    make create-tag version=20.0.0-beta.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v20.0.0-beta.1
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [x] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v20.0.0-beta.1
    - [x] Make sure that chosen tag is v20.0.0-beta.1, target is main, and previous tag is vX.Y.[Z-1]
    - [x] Add the respective `CHANGELOG.md` section from merged PR
    - [x] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [x] Set as a pre-release / as the latest release
    - [x] Publish release
- [x] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v20.0.0-beta.1
    - [x] Copy the full content from the release description of the previous step
    - [x] Set as a pre-release / as the latest release
    - [x] Publish release
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Major (30)` to `v20.0.0-beta.1` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Beta (30)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v20.0.0-beta.1` to `💚 Next Beta (30)`
- [x] Close the `v20.0.0-beta.1` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
- [x] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)
