### ISSUE TITLE
🚀 Release todo 20.0.0-rc.4

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/spreed#13205]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [ ] Check there are no pending backports:
  - [ ] https://github.com/nextcloud/spreed/labels/backport-request
- [ ] Check all milestones don't have priority issues still open
    - [ ] 
- [ ] Check there are no important PRs open against the branch
    - [ ] 
  - [ ] https://github.com/nextcloud/spreed/pulls?q=is%3Apr+is%3Aopen+base%3Astable30
- [ ] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
  
    - [ ] 
- [ ] Merge the PR

## 🚀 v20.0.0-rc.4
- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable30
    git pull origin stable30
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v20.0.0-rc.4` will be automatically added to the tag)
    ```sh
    make create-tag version=20.0.0-rc.4
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v20.0.0-rc.4
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```
- [ ] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v20.0.0-rc.4
    - [ ] Make sure that chosen tag is v20.0.0-rc.4, target is stable30, and previous tag is v20.0.0-rc.3
    - [ ] Add the respective `CHANGELOG.md` section from merged PR
    - [ ] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed

        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v20.0.0-rc.4
    - [ ] Copy the full content from the release description of the previous step
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `💚 Next Patch (30)` to `v20.0.0-rc.4` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💚 Next Patch (30)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v20.0.0-rc.4` to `💚 Next Patch (30)`
- [ ] Close the `v20.0.0-rc.4` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
- [ ] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)
