### ISSUE TITLE
Release todo list 18.0.12, 19.0.10 and 20.0.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#13505]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [ ] Check there are no pending backports:
    - [ ] https://github.com/nextcloud/spreed/labels/backport-request
- [ ] Check all milestones don't have priority issues still open
    - [ ] https://github.com/nextcloud/spreed/milestone/271
    - [ ] https://github.com/nextcloud/spreed/milestone/277
    - [ ] https://github.com/nextcloud/spreed/milestone/276
- [ ] Check there are no important PRs open against the branch
    - [ ] 
    - [ ] https://github.com/nextcloud/spreed/pulls?q=is%3Apr+is%3Aopen+base%3Astable28
    - [ ] https://github.com/nextcloud/spreed/pulls?q=is%3Apr+is%3Aopen+base%3Astable29
    - [ ] https://github.com/nextcloud/spreed/pulls?q=is%3Apr+is%3Aopen+base%3Astable30
- [ ] On first RC of a major release
    - [ ] Create `New in Talk 18` entries in the `Talk updates ✅` conversation
    - [ ] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [ ] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch
- [ ] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
     
    - [ ] 
- [ ] Merge the PR

## 🚀 v18.0.12
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable28
    git pull origin stable28
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v18.0.12` will be automatically added to the tag)
    ```sh
    make create-tag version=18.0.12
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v18.0.12
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [ ] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v18.0.12
    - [ ] Make sure that chosen tag is v18.0.12, target is stable28, and previous tag is v18.0.11
    - [ ] Add the respective `CHANGELOG.md` section from merged PR
    - [ ] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v18.0.12
    - [ ] Copy the full content from the release description of the previous step
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `🧡 Next Patch (28)` to `v18.0.12` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `🧡 Next Patch (28)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v18.0.12` to `🧡 Next Patch (28)`
- [ ] Close the `v18.0.12` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
- [ ] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)

## 🚀 v19.0.10
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable29
    git pull origin stable29
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v19.0.10` will be automatically added to the tag)
    ```sh
    make create-tag version=19.0.10
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v19.0.10
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [ ] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v19.0.10
    - [ ] Make sure that chosen tag is v19.0.10, target is stable29, and previous tag is v19.0.9
    - [ ] Add the respective `CHANGELOG.md` section from merged PR
    - [ ] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v19.0.10
    - [ ] Copy the full content from the release description of the previous step
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `💚 Next Patch (29)` to `v19.0.10` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💚 Next Patch (29)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v19.0.10` to `💚 Next Patch (29)`
- [ ] Close the `v19.0.10` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
- [ ] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)

## 🚀 v20.0.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
    - [ ] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Make sure the printed version matches the info.xml version
    npm version --no-git-tag-version $(xmllint --xpath '/info/version/text()' appinfo/info.xml)
    ```
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable30
    git pull origin stable30
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [ ] Create tag (note that the leading `v` in `v20.0.1` will be automatically added to the tag)
    ```sh
    make create-tag version=20.0.1
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v20.0.1
    ```
    Make sure you have access rights to the remote repository, and it is set up on your machine:
    ```sh
    git remote add releases git@github.com:nextcloud-releases/spreed.git
    ```    
- [ ] Prepare a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v20.0.1
    - [ ] Make sure that chosen tag is v20.0.1, target is stable30, and previous tag is v20.0.0
    - [ ] Add the respective `CHANGELOG.md` section from merged PR
    - [ ] Use the **Generate release notes** button and wrap the output result into
        ```
        ## What's Changed
        
        <details>
        	<!-- insert the output here -->
        </details>
        ```
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Prepare a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v20.0.1
    - [ ] Copy the full content from the release description of the previous step
    - [ ] Set as a pre-release / as the latest release
    - [ ] Publish release
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [ ] Rename milestone `💙 Next Patch (30)` to `v20.0.1` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💙 Next Patch (30)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [ ] Move all open PRs and issues from milestone `v20.0.1` to `💙 Next Patch (30)`
- [ ] Close the `v20.0.1` milestone
- [ ] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [ ] In case there were security issues fixed ping the security team
- [ ] Post the changelog in [💬 Talk team public 👥](https://cloud.nextcloud.com/call/c7fz9qpr)
