### ISSUE TITLE
Chat in file sidebar todo

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#2619]
- [ ] If the chat tab is opened again after a file is shared the button will still be "_Share this file_" instead of "_Join conversation_". It seems that the FileInfo is not properly updated in the server when a file is shared (or unshared). This needs to be further investigated, but it seems to be an issue in the server and not in Talk.
- [X] The chat tab is shown for folders with a "_Conversations are not available for folders_" message (not localized). The tab will not be shown once #2605 is merged, but as it requires a change in server which was not ready for beta 3 that temporary warning is shown for now (to be able to release a Talk version that can be used with beta 3 of server).
- [x] Chat input is not focused after the chat view is shown.
- [x] This only adds the chat tab; calls in the sidebar will be added back in a different pull request.
