### ISSUE TITLE
Spreed for Nextcloud 13

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#347]
## Features
- [x] Ownership and moderation #297 @nickvergessen
- [x] Password protection for public calls #36 @nickvergessen
- [x] Scheduled calls / waiting lobby #431  @nickvergessen
- [ ] Calendar integration https://github.com/nextcloud/calendar/issues/563 @leonklingele
- [x] Multi STUN/TURN/etc. servers #427 @nickvergessen

### Possible additional features
- [ ] Federated calls
- [ ] Extend automated testing
- [x] Activity for calls #236 

## Apps
- [x] Android app #338 https://github.com/nextcloud/talk-android @mario 
- [x] iOS app: https://github.com/nextcloud/spreed-ios @Ivansss 
- [ ] Desktop app

**Comment by e-alfred** [comment]
Will chat support also be part of the new release? Or is that triaged until later?

**Comment by nickvergessen** [comment]
I think other people will work on that, so not sure.

**Comment by leonklingele** [comment]
I have created a separate issue for the `Calendar integration ` [here](https://github.com/nextcloud/calendar/issues/563) and took ownership of that task.
