### ISSUE TITLE
Chat integration

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#395]
# Nextcloud 13
## Must have:

- [X] Basic chat: tab in the right sidebar of the Spreed app for each room; follow appearance of comments tab in Files app. Messages are stored in database.
  - [X] Define API.
  - [X] Basic backend with short polling in the server (#429).
  - [X] Basic frontend in Spreed app using long polling to the server. (#462)

## Nice to have:

- [ ] More advanced backend using shared memory and semaphores to send messages between PHP processes and avoid needing to poll the database; check if there is any other higher level PHP extension or library that could be used. 

- [x] Notifications are sent to users when their name is mentioned. (#460)

- [ ] Chat messages are searchable.

# Future:

- Federation, so people in the same chat room can be on different Nextcloud servers.

- Make possible to connect to the chat from third-party clients, like XMPP or Matrix.

- Nextcloud integration, like starting a chat from the contacts app.

- One on one chat available over any Nextcloud app.

- Advanced display of content in the chat view, like previews of photos.

**Comment by nickvergessen** [comment]
Closing the 13 ticket, since the must haves are in (apart from #544 )
