### ISSUE TITLE
Sidebar improvements

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#399]
## Todos
- [x] Currently the complete list is refreshed for the moderator when they change another participant => #439 
- [x] When a user is promoted/demoted by another moderator, the sidebar should rerender. => #439 
- [x] Renaming should be in the sidebar #440 
- [x] Share link should be in the sidebar #440 
- [x] Adding participants should be in the participants tab view #440 
- [x] Guests are displayed wrongly in the sidebar => #410
