### ISSUE TITLE
[Template] Release todo X.Y.Z

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5879]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## General

- [ ] On master create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [ ] Create a PR against master  `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [ ] Merge the PR
- [ ] Backport the changelog to the respective branches
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
- [ ] Merge the backports

## For each maintenance release
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Make sure you pull the latest stable branch:
    ```sh
    git pull origin stableX
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [ ] Build production javascript:
    ```sh
    make build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [ ] Build release tarball
    ```sh
    make release version=X.Y.Z
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [ ] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=X.Y.Z`
- [ ] Edit the milestone name to `vX.Y.Z`
- [ ] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks)
- [ ] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [ ] Close the `vX.Y.Z` milestone
- [ ] In case there were security issues fixed ping the security team

**Comment by nickvergessen** [comment]
# Legacy before 23


## 🚀 vX.Y.Z
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [ ] Bump the version in `appinfo/info.xml`
- [ ] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stableX.Y
    git pull origin stableX.Y
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [ ] Build release tarball
    ```sh
    make release version=X.Y.Z
    ```
- [ ] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [ ] Add the respective `CHANGELOG.md` section
    - [ ] Upload the tarball from `build/artifacts/`
    - [ ] Add the respective `CHANGELOG.md` section
- [ ] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [ ] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [ ] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=X.Y.Z`
- [ ] Rename milestone `💚 Next Patch (X)` to `vX.Y.Z`
- Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks)
    - [ ] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [ ] Close the `vX.Y.Z` milestone
- [ ] In case there were security issues fixed ping the security team

**Comment by Antreesy** [comment]
# Alternative commands for template issue - to automate later?

- [ ] Get the ID of the milestone to release in https://github.com/nextcloud/spreed/milestones
    ```sh
    gh api 'repos/nextcloud/spreed/milestones?state=open&per_page=100' --paginate \
        --jq '.[] | select(.title | endswith("Next Patch (X)")) | "\(.number)\t\(.title)"'
    ```
    - [ ] The output must be exactly one line, for example `373 🏖️ Next Patch (34)`. If it is empty or has more than one line, fix the milestones before you continue.
    - [ ] Note the number as `<MILESTONE_ID>` and the title as `<OLD_TITLE>`. Use them in the steps below.
- [ ] Rename milestone `<OLD_TITLE>` to `vX.Y.Z`
    ```sh
    gh api --method PATCH repos/nextcloud/spreed/milestones/<MILESTONE_ID> \
        -f title="vX.Y.Z" --jq .title
    ```
    The command prints the new title. It must be `vX.Y.Z`.

    Unless last release of the stable branch:
    - [ ] Create a follow-up milestone for `<OLD_TITLE>` (Due date in ~4 weeks, ~1 week for beta/RC)
        ```sh
        # For a beta/RC use '+1 week' instead of '+4 weeks'
        gh api --method POST repos/nextcloud/spreed/milestones \
            -f title="<OLD_TITLE>" \
            -f due_on="$(date -u -d '+4 weeks' +%Y-%m-%dT00:00:00Z)" \
            --jq '"\(.number)\t\(.title)\t\(.due_on)"'
        ```
        - [ ] Note the printed number as `<FOLLOWUP_ID>`.
    - [ ] Move all open issues and pull requests from milestone `vX.Y.Z` to `<OLD_TITLE>`: https://github.com/nextcloud/spreed/issues?q=state%3Aopen%20milestone%3AvX.Y.Z
        ```sh
        gh api 'repos/nextcloud/spreed/issues?milestone=<MILESTONE_ID>&state=open&per_page=100' \
            --paginate --jq '.[].number' \
            | xargs -r -I{} gh api --method PATCH repos/nextcloud/spreed/issues/{} \
                -F milestone=<FOLLOWUP_ID> --jq .number
        ```
        This endpoint returns pull requests as well, so one command covers both.
        Do not add `xargs -P`, because GitHub rate limits concurrent writes.
    - [ ] Check the milestone is empty. The command prints nothing when it is:
        ```sh
        gh api 'repos/nextcloud/spreed/issues?milestone=<MILESTONE_ID>&state=open&per_page=100' \
            --paginate --jq '.[].number'
        ```
- [ ] Close the `vX.Y.Z` milestone
    ```sh
    gh api --method PATCH repos/nextcloud/spreed/milestones/<MILESTONE_ID> \
        -f state=closed --jq .state
    ```
    The command prints `closed`.
