### ISSUE TITLE
Release todo 12.0.0-rc.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5910]
https://github.com/nextcloud/spreed/milestone/82

## 💺 Preparation

- [x] On master create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master  `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [x] Merge the PR https://github.com/nextcloud/spreed/pull/5913
- [x] Backport the changelog to the respective branches https://github.com/nextcloud/spreed/pull/5916
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backports

## 🚀 For each release

- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable22
    git pull origin stable22
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Build release tarball
    ```sh
    make release version=X.Y.Z
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases vX.Y.Z
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=X.Y.Z`
- [x] Edit the milestone name to `vX.Y.Z`
- [x] Create a follow up milestone for `💚 Next Patch (X)` (Due date in ~4 weeks)
- [x] Move all open PRs and issues from milestone `vX.Y.Z` to `💚 Next Patch (X)`
- [x] Close the `vX.Y.Z` milestone
- [x] If the release was on a `stableX.1` branch, backport it to `stableX`
    ```sh
    git checkout stableX.1
    git pull origin stableX.1
    git checkout stableX
    git pull origin stableX
    git merge --no-ff origin/stableX.1
    ```
- [x] In case there were security issues fixed ping the security team
