### ISSUE TITLE
Release todo 12.0.0

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#5953]
* https://github.com/nextcloud/spreed/milestone/106

## 💺 Preparation

- [x] On master create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master  `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [x] Merge the PR
- [x] Backport the changelog to the respective branches
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backports

## 🚀 For each maintenance release
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Make sure you pull the latest stable branch:
    ```sh
    git pull origin stable22
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Build release tarball
    ```sh
    make release version=12.0.0
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v12.0.0
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=12.0.0`
- [x] Edit the milestone name to `v12.0.0`
- [x] Create a follow up milestone for `💙 Next Patch (22)` (Due date in ~4 weeks)
- [x] Move all open PRs and issues from milestone `v12.0.0` to `💙 Next Patch (22)`
- [x] Close the `v12.0.0` milestone
- [x] If the release was the first on a `stable22` branch, branch off  `stable22.1`
    ```sh
    git checkout stable22
    git checkout -b stable22.1
    git push origin stable22.1
    git push origin stable22
    ```
- [x] If the release was on a `stable22.1` branch, backport it to `stable22`
    ```sh
    git checkout stable22.1
    git pull origin stable22.1
    git checkout stable22
    git pull origin stable22
    git merge --no-ff origin/stable22.1
    ```
- [x] In case there were security issues fixed ping the security team
