### ISSUE TITLE
Allow to mention groups in the chats when they are a member of the conversation

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/spreed#6339]
In group chats I cannot mention a group that is added to this chat.

## Todo

- [x] Requires https://github.com/nextcloud/server/pull/29140
- [x] Mention API returns groups which are tracked
- [x] When generating notifications for mentions group members need to be notified
    - [x] Check for conflict with replying
    - [x] Check that the group is a member of the room
- [x] Render group mention suggestion in the input field with `icon-group-forced-white` + group displayname
- [x] Render group mentions in messages with `icon-group-forced-white` + group displayname
- [ ] #9073
- [x] Create issues in iOS and Android to handle those cases
    - [ ] https://github.com/nextcloud/talk-android/issues/2860
    - [ ] https://github.com/nextcloud/talk-ios/issues/1135
- [ ] #9074

**Comment by nickvergessen** [comment]
Now that we store group memberships that totally makes sense

**Comment by nickvergessen** [comment]
Moved open tasks to follow ups
