### ISSUE TITLE
Release todo 11.3.3

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6386]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] On master create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master  `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [x] Merge the PR
- [x] Backport the changelog to the respective branches https://github.com/nextcloud/spreed/pull/6385
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backports

## 🚀 v11.3.3
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable21
    git pull origin stable21
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [x] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Build release tarball
    ```sh
    make release version=11.3.3
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v11.3.3
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=11.3.3`
- [x] Rename milestone `💚 Next Patch (21)` to `v11.3.3`
- [x] Create a follow up milestone for `💚 Next Patch (21)` (Due date in ~4 weeks)
- [x] Move all open PRs and issues from milestone `v11.3.3` to `💚 Next Patch (21)`
- [x] Close the `v11.3.3` milestone
- [x] In case there were security issues fixed ping the security team
