### ISSUE TITLE
Release todo 11.3.4 and 12.2.2

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#6666]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check all milestones don't have priority issues still open
- [x] On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master  `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [x] Merge the PR

## 🚀 v11.3.4
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable21
    git pull origin stable21
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [x] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Build release tarball
    ```sh
    make release version=11.3.4
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v11.3.4
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=X.Y.Z`
- [x] Rename milestone `💚 Next Patch (21)` to `v11.3.4`
- [x] Create a follow up milestone for `💚 Next Patch (21)` (Due date in ~4 weeks)
- [x] Move all open PRs and issues from milestone `v11.3.4` to `💚 Next Patch (21)`
- [x] Close the `v11.3.4` milestone
- [x] In case there were security issues fixed ping the security team

## 🚀 v12.2.2
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable22
    git pull origin stable22
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [x] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Build release tarball
    ```sh
    make release version=12.2.2
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v12.2.2
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - upload the tarball from `build/artifacts/`
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Upload the app release in the appstore: https://apps.nextcloud.com/developer/apps/releases/new
    - Link to the tarball on https://github.com/nextcloud-releases/spreed/releases
    - Signature that was printed by `make release version=X.Y.Z`
- [x] Rename milestone `💙 Next Patch (22)` to `v12.2.2`
- [x] Create a follow up milestone for `💙 Next Patch (22)` (Due date in ~4 weeks)
- [x] Move all open PRs and issues from milestone `v12.2.2` to `💙 Next Patch (22)`
- [x] Close the `v12.2.2` milestone
- [x] In case there were security issues fixed ping the security team

**Comment by nickvergessen** [comment]
> Something went really wrong, and we can’t process that file. 

Github fails on uploading the archive of 12.2.2
Will retry tomorrow

**Comment by nickvergessen** [comment]
AWS was down. Uploaded correctly today
