### ISSUE TITLE
Release todo 14.0.0-beta1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7123]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check all milestones don't have priority issues still open
- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/pulls?q=is%3Apr+label%3Abackport-request+is%3Aclosed
- [x] On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile` https://github.com/nextcloud/spreed/pull/7124
    ```sh
    make appstore
    ```
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release https://github.com/nextcloud/spreed/pull/7122
- [x] Merge the PRs

## 🚀 v14.0.0-beta.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout master
    git pull origin master
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [x] Build production javascript:
    ```sh
    make build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag
    ```sh
    make create-tag version=14.0.0-beta.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v14.0.0-beta.1
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
- [x] Rename milestone `💛 Next Major (24)` to `v14.0.0-beta.1`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💛 Next RC (24)` (Due date in ~4 weeks)
    - [x] Move all open PRs and issues from milestone `v14.0.0-beta.1` to `💛 Next RC (24)`
- [x] Close the `v14.0.0-beta.1` milestone
- [x] In case there were security issues fixed ping the security team
