### ISSUE TITLE
 Release todo 14.0.0-rc.3

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7202]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [X] Check all milestones don't have priority issues still open
- [X] Check there are no pending backports: https://github.com/nextcloud/spreed/pulls?q=is%3Apr+label%3Abackport-request+is%3Aclosed
- [X] On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [X] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
- [X] Merge the PR

## 🚀 v14.0.0-rc.3
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [X] Backport the changelog
    - [X] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [X] Bump the version in `appinfo/info.xml`
- [X] Merge the backport
- [X] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable24
    git pull origin stable24
    ```
- [X] Clean the dev instance and update all dependencies with the lock file versions:
    ```sh
    make dev-setup
    ```
- [X] Build production javascript:
    ```sh
    make build-js-production
    ```
- [X] Do a quick smoke test by starting a call with:
    - [X] Chrome
    - [ ] Edge
    - [X] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [X] Create tag
    ```sh
    make create-tag version=14.0.0-rc.3
    ```
- [X] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v14.0.0-rc.3
    ```
- [X] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/tag/v14.0.0-rc.3
- [X] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/tag/v14.0.0-rc.3
    - add the respective `CHANGELOG.md` section
    - a link to the binary from the releases-repo as description
    - ⚠️  Do not re-upload the binary here.
        - The package will be automatically built, see https://github.com/nextcloud-releases/spreed/actions
- [X] Rename milestone `💛 Next RC (24)` to `v14.0.0-rc.3`
- Unless last release of the stable branch:
    - [X] Create a follow up milestone for `💛 Next RC (24)` (Due date in ~1 weeks)
    - [X] Move all open PRs and issues from milestone `v14.0.0-rc.3` to `💛 Next RC (24)`
- [X] Close the `v14.0.0-rc.3` milestone
- [X] In case there were security issues fixed ping the security team
