### ISSUE TITLE
Parsing issues of HTML elements - Admin settings

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#7651]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Server
- [x] Element `#app-content`: Error: Attribute touch-action not allowed on element div at this point. => https://developer.mozilla.org/de/docs/Web/CSS/touch-action Seems to be valid, so might be an issue of the validator

### General settings (Multiselect)
- [x] Error: Bad value for attribute name on element input: Must not be empty. https://github.com/nextcloud/spreed/pull/7652
- [ ] Error: Bad value nope for attribute autocomplete on element input: The string nope is not a valid autofill field name. https://github.com/nextcloud/nextcloud-vue/issues/2891
- [ ] Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.) https://github.com/nextcloud/nextcloud-vue/issues/2891
- [x] Error: No p element in scope but a p end tag seen. https://github.com/nextcloud/spreed/pull/7652

### Limit to groups (Multiselect)
- [x] Error: Bad value for attribute name on element input: Must not be empty. https://github.com/nextcloud/spreed/pull/7652
- [ ] Error: Bad value nope for attribute autocomplete on element input: The string nope is not a valid autofill field name. https://github.com/nextcloud/nextcloud-vue/issues/2891
- [ ] Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.) https://github.com/nextcloud/nextcloud-vue/issues/2891
- [x] Error: No p element in scope but a p end tag seen. https://github.com/nextcloud/spreed/pull/7652

### Commands
- [x] Error: Attribute fragment not allowed on element div at this point. https://github.com/nextcloud/spreed/pull/7652

### Hosted high-performance backend 
- [x] Error: Attribute placeholder not allowed on element select at this point https://github.com/nextcloud/spreed/pull/7652

**Comment by nickvergessen** [comment]
> Error: Bad value for attribute name on element input: Must not be empty.

This was brought in upstream:
https://github.com/shentao/vue-multiselect/blob/2.1.6/src/Multiselect.vue#L157-L165

But is not named or piped through by the Vue lib.

Fixable with a patch in Talk just adding something like:
```html
				name="default_group_notification"
```

Maybe we should add this as required prop or fall back to the id value?

> Error: Bad value nope for attribute autocomplete on element input: The string nope is not a valid autofill field name.

https://github.com/shentao/vue-multiselect/blob/2.1.6/src/Multiselect.vue#L51

Upstream issue again, but changed to `off` in master:
https://github.com/shentao/vue-multiselect/pull/1064

But there was no release since: https://github.com/shentao/vue-multiselect/issues/1518

> Error: Element div not allowed as child of element span in this context. (Suppressing further errors from this subtree.)

Comes from
https://github.com/nextcloud/nextcloud-vue/blob/a08bfb147a970a34abd0881ecd305f5f78b699cc/src/components/Multiselect/EllipsisedOption.vue#L24

So would need someone to look into it and transform it to a span or something.

>  Error: No p element in scope but a p end tag seen.

Multiselect must not be used inside a p tag.

**Comment by nickvergessen** [comment]
> ❌ Error: Attribute fragment not allowed on element div at this point.

* https://github.com/Thunberg087/vue-fragment/issues/51 unanswered since ~2 years. There is a comment with a follow up lib that fixes this.

**Comment by nickvergessen** [comment]
Seems to not be an issue anymore
