### ISSUE TITLE
Talk design review Tue 6/09

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#7866]
Talk new design review

- [x] Placeholders are too dark (not present on master)
- [x] Conversation settings has too much space at the bottom (not present on master)
- [x] "Talk settings" text should be left aligned with other text, icon should be center aligned with avatars #7870 
- [x] Background on search bar is grey in video call (not present on master)
- [x] Unread counter is in dark mode even though light theme is applied (not present on master)
- [x] When scrolling in conversation list the line below the search bar is light, possibly remove it #7870 
- [x] Sidebar icon should be visible #7871
- [x] Video call view with multiple people: extends further than body container, sidebar overlaps video call #7869
- [x] Video call view grey background --> half transparent black background #7873
- [x] Add titles to settingsdialogs #7875 
- [ ] Bg too harsh for focus and hover of icons in video call view #7703
- [x] Menus and popovers that extend past the body container are clipped #7876
- [x] Add titles to settings sections
- [ ] Action menu is not accessible via tabbing
- [ ] Focus feedback on tabbing

Search results in navigation:

- [x] Alignment: align headings to left of avatar, also in search results in participant list #7870 
- [ ] ~~New text file from conversation: height is till edge of screen~~
- [x] Clicking on 3 dot menu on a message opens the action menu behind the sidebar and text input
- [x] Similar issue for action menu for each participant in the sidebar
- [x] Line between preview and text when

**- nc/vue**

- [ ] Tabbing in conversation list has 3 tab stops for each item, should be just 2 tab stops
- [ ] Spacing: too much space between sections
- [ ] Color: Headings contrast is not enough, change to --color-main-text, also in search results in participant list
- [ ] Scrollbar right edge should be exactly where right edge of conversation list, possibly make it wider? (requires removing padding in the app navigation)
- [ ] Contrast too less for subline of messages, darken the color. Possibly a CSS rule or something (for all navigation items that uses maxcontrast)

**Comment by nickvergessen** [comment]
> New text file from conversation: height is till edge of screen

This is the viewer and expected. We will not interfer there.

**Comment by nickvergessen** [comment]
> Tabbing in conversation list has 3 tab stops for each item, should be just 2 tab stops

Only has 2 stops here, but they both open the conversation, none is opening the menu

**Comment by nickvergessen** [comment]
>  Action menu is not accessible via tabbing
Focus feedback on tabbing

I think the remaining 2 points are also bugs in the vue lib. So then I would close this? cc @marcoambrosini
