### ISSUE TITLE
Release todo 15.0.0-beta.3

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/spreed#7880]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [X] Check all milestones don't have priority issues still open
    - [X] https://github.com/nextcloud/spreed/milestone/156
- [X] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [X] On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [X] https://github.com/nextcloud/spreed/pull/7881
- [x] Merge the PR

## 🚀 v15.0.0-beta.3
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout master
    git pull origin master
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make clean-dev composer-install-production npm-init build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag
    ```sh
    make create-tag version=15.0.0-beta.3
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v15.0.0-beta.3
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Beta (25)` to `v15.0.0-beta.3`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next RC (25)` (Due date in ~4 weeks)
    - [x] Move all open PRs and issues from milestone `v15.0.0-beta.3` to `💚 Next RC (25)`
- [x] Close the `v15.0.0-beta.3` milestone
- [x] In case there were security issues fixed ping the security team
