### ISSUE TITLE
⛵ Release todo 12.2.8, 13.0.10, 14.0.6 and 15.0.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8276]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/150
    - [x] https://github.com/nextcloud/spreed/milestone/158
    - [x] https://github.com/nextcloud/spreed/milestone/159
    - [x] https://github.com/nextcloud/spreed/milestone/165
- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [x] On major releases create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [x] https://github.com/nextcloud/spreed/pull/8278
- [x] Merge the PR

## 🚀 v12.2.8
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/8282
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable22
    git pull origin stable22
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v12.2.8` will be automatically added to the tag)
    ```sh
    make create-tag version=12.2.8
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v12.2.8
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [ ] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💙 Next Patch (22)` to `v12.2.8`
- Unless last release of the stable branch:
    - [ ] Create a follow up milestone for `💙 Next Patch (22)` (Due date in ~4 weeks)
    - [ ] Move all open PRs and issues from milestone `v12.2.8` to `💙 Next Patch (22)`
- [x] Close the `v12.2.8` milestone
- [x] In case there were security issues fixed ping the security team

## 🚀 v13.0.10
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/8281
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable23
    git pull origin stable23
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v13.0.10` will be automatically added to the tag)
    ```sh
    make create-tag version=13.0.10
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v13.0.10
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (23)` to `v13.0.10`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (23)` (Due date in ~4 weeks)
    - [x] Move all open PRs and issues from milestone `v13.0.10` to `💚 Next Patch (23)`
- [x] Close the `v13.0.10` milestone
- [x] In case there were security issues fixed ping the security team

## 🚀 v14.0.6
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/8280
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable24
    git pull origin stable24
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v14.0.6` will be automatically added to the tag)
    ```sh
    make create-tag version=14.0.6
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v14.0.6
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💚 Next Patch (24)` to `v14.0.6`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💚 Next Patch (24)` (Due date in ~4 weeks)
    - [x] Move all open PRs and issues from milestone `v14.0.6` to `💚 Next Patch (24)`
- [x] Close the `v14.0.6` milestone
- [x] In case there were security issues fixed ping the security team

## 🚀 v15.0.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/8279
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable25
    git pull origin stable25
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [ ] Edge
    - [x] Firefox
    - [x] Safari
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v15.0.1` will be automatically added to the tag)
    ```sh
    make create-tag version=15.0.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v15.0.1
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💖 Next Patch (25)` to `v15.0.1`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💖 Next Patch (25)` (Due date in ~4 weeks)
    - [x] Move all open PRs and issues from milestone `v15.0.1` to `💖 Next Patch (25)`
- [x] Close the `v15.0.1` milestone
- [x] In case there were security issues fixed ping the security team
