### ISSUE TITLE
⛵ Release todo 16.0.0-beta.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#8790]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/161
- [x] On major releases
    - [x] Create a test package and check if a new development file needs to be added to the packaging exclude list in `make appstore`
        - [x] https://github.com/nextcloud/spreed/pull/8809
        - [x] https://github.com/nextcloud/spreed/pull/8814
    - [x] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch https://github.com/nextcloud/spreed/pull/8810
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [x] https://github.com/nextcloud/spreed/pull/8813
- [x] Merge the PR

## 🚀 v16.0.0-beta.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [ ] Backport the changelog
    - [ ] 
    - [ ] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout master
    git pull origin master
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascrip:
    ```sh
    make production-setup
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [ ] Safari
    - [x] Android app
    - [x] iOS app
- [x] Create tag (note that the leading `v` in `v16.0.0-beta.1` will be automatically added to the tag)
    ```sh
    make create-tag version=16.0.0-beta.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v16.0.0-beta.1
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases
    - [x] Add the respective `CHANGELOG.md` section
    - 🛑 Do **NOT** re-upload the binary here.
- [x] Rename milestone `🚀 First Final (26)` to `v16.0.0-beta.1`
- Unless last release of the stable branch:
    - [x] Create a follow up milestone for `🚀 Next Beta (26)` (Due date in ~1 weeks)
    - [x] Move all open PRs and issues from milestone `v16.0.0-beta.1` to `🚀 Next Beta (26)`
- [x] Close the `v16.0.0-beta.1` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
