### ISSUE TITLE
Breakout rooms design review

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/spreed#8896]
# Breakout rooms design review

28th February 2023:

## Overall

- [x] Think about restructuring menu and moving items around in the future releases https://github.com/nextcloud/spreed/issues/9005
- [x] 🏃‍♂️ Change icon to [https://fonts.google.com/icons?selected=Material Icons%3Aworkspaces%3A](https://fonts.google.com/icons?selected=Material%20Icons%3Aworkspaces%3A) – also of individual breakout rooms, only have 1 icon, not 2 different ones
#8900 
- [x] 🏃‍♂️ Change wording from "Setup breakout rooms" to "Set up breakout rooms", as it’s a verb not a noun. In menu and modal #8901

## Accessibility

* [x] Radio buttons need to be in a `fieldset` to group them semantically

## Setup modal #8902

- [x] 🏃‍♂️ Line break after "Number of breakout rooms"
- [x] 🏃‍♂️ Heading "Assignment method" before radio buttons

## Manual assignment modal #8903

* [x] Rooms should be collapsible
* [x] "Create breakout rooms" non-primary until everyone is assigned
* [x] "Assign" --> primary button
* [x] Avatars did not show / placeholder avatars only

## Sidebar view

* [ ] In the future, get rid of specific "Breakout rooms" tab and combine it into "Participants" tab up top. https://github.com/nextcloud/spreed/issues/9005
* [x] 🏃‍♂️ When inside a BR, show "Go back to main room" button in
* [x] 🏃‍♂️ Layout for row of buttons
  - [x] First row:
    - [x] Start/end session button, full width
    - [x] if moderator: show "Back to main room" on the same row, 2 half-width buttons
  - [x] "Message all rooms" almost-full width button on the next row, with participant assignment icon-only button next to it
  - [x] Participant assignment button:
    - [x] "Manage breakout rooms"
    - [x] Cog icon
  - [x] Message all rooms icon --> paper plane icon
* [x] 🏃‍♂️ Icons for start/end session button
  - [x] 🏃‍♂️ Start session [https://fonts.google.com/icons?selected=Material Icons%3Aworkspaces%3A](https://fonts.google.com/icons?selected=Material%20Icons%3Aworkspaces%3A)
  - [x] 🏃‍♂️ End session [https://fonts.google.com/icons?selected=Material Icons%3Aworkspaces_outline%3A](https://fonts.google.com/icons?selected=Material%20Icons%3Aworkspaces_outline%3A)
* [x] 🏃‍♂️ Icon for "Message all rooms": [https://fonts.google.com/icons?selected=Material Icons%3Asend%3A](https://fonts.google.com/icons?selected=Material%20Icons%3Asend%3A)
* [x] "Join room" button can be a text only button
* [x] All icons in a row need to be horizontally aligned
* [x] All text should be left aligned (Room 1, participants, Room 2, participants)
* [x] More whitespace between BRs
* [x] All 3dot menu icons should be center aligned

**Comment by marcoambrosini** [comment]
All done but the combining of braekout rooms and participants tab, which requires solving some design problems first. Discussion here https://github.com/nextcloud/spreed/issues/9005

**Comment by nickvergessen** [comment]
Good Job 🎉
