### ISSUE TITLE
🖼️ Conversation avatars

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/spreed#927]
Update as per last discussions:

- [ ] Cropper like in user avatar
- [ ] Automatic shrinking
- [ ] Transparency => white background
- [ ] Animation not allowed
- [ ] One endpoint to rule them all :ring: : user avatar, file mimetype-icon, conversation-image****

Not available for one-to-one, file-conversations and video-verification
No mashing of user avatars as they would need updating and tracking when a user changes their avatar

---

### Work packages

- [x] Server API @vitormattos 
  - [x] https://github.com/nextcloud/spreed/pull/8333
  - [x] https://github.com/nextcloud/spreed/issues/8443
- [ ] Frontend
  - https://github.com/nextcloud/spreed/issues/8334
- [ ] Android
  - https://github.com/nextcloud/talk-android/issues/2555
- [ ] iOS
  - https://github.com/nextcloud/talk-ios/issues/979

**Comment by nickvergessen** [comment]
* Not available for one-to-one, file-conversations and video-verification

**Comment by nickvergessen** [comment]
* No mashing of user avatars as they would need updating and tracking when a user changes their avatar

**Comment by nickvergessen** [comment]
- [ ] Cropper like in user avatar
- [ ] Automatic shrinking
- [ ] Transparency => white background
- [ ] Animation not allowed

**Comment by Tachi107** [comment]
> * No mashing of user avatars as they would need updating and tracking when a user changes their avatar

Can't the refetch be done manually? Like an option in the conversation settings to update the group picture

**Comment by nickvergessen** [comment]
> Can't the refetch be done manually? Like an option in the conversation settings to update the group picture

Well, then when a user changes their avatar they need to ask all moderators to update it and so on.

**Comment by Tachi107** [comment]
> > Can't the refetch be done manually? Like an option in the conversation settings to update the group picture
> 
> Well, then when a user changes their avatar they need to ask all moderators to update it and so on.

Yeah, that could be a problem in big conversations, but at the same time I see the mashing of user avatars as something that would be primarily used in small groups, like a chat of ten friends, and asking a friend to push a button doesn't sound like a big issue

**Comment by nickvergessen** [comment]
> Yeah, that could be a problem in big conversations, but at the same time I see the mashing of user avatars as something that would be primarily used in small groups, like a chat of ten friends, and asking a friend to push a button doesn't sound like a big issue

yeah, but since we always have to consider all Nextcloud installations, from 1 person to big companies, we will do what all bigger messengers do: No mash-up but just the current default icon.

**Comment by Tachi107** [comment]
Mh, okay, still better than not having the possibility to set a group picture at all :)

**Comment by danir-de** [comment]
Why isn't this feature more prioritized? Especially when you have many group chats it becomes very cumbersome to tell apart different chats - they're all indistinguishable optically. 

Also the following points don't seem to be thought through completely:
- Animated avatars are becoming a thing and can help to promote a chat or meeting
- Transparent images are very useful, especially when thinking about images that are optimized for light and dark themes. If an image is supposed to have a background, it contains a background, no need to create unessecairy barriers and complexity.

**Comment by nickvergessen** [comment]
> Why isn't this feature more prioritized?

It's currently on our todo list in the planing board, one of 25 items. That's as much priority an issue can get. We are only a limited amount of people working on the Talk app and everyone has their expertise in a certain area, so that's just how it is.

We are open source, so if you feel like you can do it feel free to pick up the closed pull requests from above and finish the open points in them.

> Especially when you have many group chats it becomes very cumbersome to tell apart different chats - they're all indistinguishable optically.

---|---
---|---
It's a pain for us as well, every day. My personal workaround is using emojis in the titles | ![Bildschirmfoto von 2022-03-01 10-13-20](https://user-images.githubusercontent.com/213943/156140268-132a69d8-9777-42e6-9ea2-a81b57f89e4a.png)

**Comment by danir-de** [comment]
> It's currently on our todo list in the planing board, one of 25 items. That's as much priority an issue can get. We are only a limited amount of people working on the Talk app and everyone has their expertise in a certain area, so that's just how it is.
> 
> We are open source, so if you feel like you can do it feel free to pick up the closed pull requests from above and finish the open points in them.

I know that and that shouldn't be an insult! 
It's just that this feature has been open and was postponed for a long time and went from the **💚 Next Major** milestone to **[💔 Backlog](https://github.com/nextcloud/spreed/milestone/3)** - removing it from the focus of development. Would my coding capabilities and time ressources be enough, I would have committed already, so instead of making more work on this end than I can solve, I'd rather try to revive and help with posting constructive feedback for existing issues.

> It's a pain for us as well, every day. My personal workaround is using emojis in the titles

That's a good idea! 🤯

**Comment by R7JANV1** [comment]
Is there any progress here yet?

**Comment by nickvergessen** [comment]
## API Specs

- [ ] We need OCS API, suggestion: `/api/{apiVersion}/room/{token}/image` - Similar to https://github.com/nextcloud/spreed/blob/master/lib/Controller/TempAvatarController.php
  - [ ] POST a new image
    - [ ] Needs to validate the file is an image
    - [ ] Needs to validate the image is a square and of a supported type (check User avatar code for what we should allow)
    - [ ] File should be stored with `OCP\Files\IAppData` with conversation token + file type as name
  - [ ] DELETE to remove an image
  - [ ] GET which serves the image as FileDisplayResponse
    - [ ] Not sure if that works as OCSController, if it does not we need another Controller with another route.
    - [ ] If AppData does not have a file with the conversation name, we fall back to returning an icon based on the conversation type
    - [ ] If the conversation is a one-to-one conversation we fall back to the user avatar?

**Comment by e-caste** [comment]
2 cool frontend features that I don't see mentioned above and that I think could be useful:
1. Telegram allows to "Search Web" when setting a group picture (e.g. I want to set it to a picture of a horse but I don't have one ready, I can just skip the step of downloading it locally and then setting it from my gallery)
2. Whatsapp also allows to set an "Emoji & Sticker". For a quick group chat creation process I think that could be a very nice UX addition and probably wouldn't be too hard to implement (last famous words?) in the sense that the user can spawn an emoji picker and choose from those. Maybe a nice improvement over using the rendered emojis, since they're low resolution, would be to use a high resolution emoji pack such as https://twemoji.twitter.com which also contains SVG versions. This is similar to the workaround @nickvergessen is using (setting emojis in the chat titles), but would be an official implementation.

**Comment by nickvergessen** [comment]
Reopening meta ticket until the dedicated issues got resolved

**Comment by nickvergessen** [comment]
@e-caste for 1. I can say that we are not going to add this because it creates security issues on the way.
2. sounds like a good/funny follow up idea, but it will not be part of the initial feature. Can you create a new ticket?

**Comment by Kitanit** [comment]
As I understand it will not work in NC 26, only 27+ ?
