### ISSUE TITLE
Vue 3 Migration

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/spreed#9448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

# ⚰️ Vue 2 End-Of-Life - 2024 

**Vue 2 will reach End of Life (EOL) on December 31st, 2023:** https://v2.vuejs.org/lts/

See also: https://v3-migration.vuejs.org/

## Dependency compatibilities

Nextcloud Dependencies:

- [x] `@nextcloud/vue`: https://github.com/nextcloud/nextcloud-vue/issues/2154
- [x] `nextcloud-vue-collections`: https://github.com/nextcloud-libraries/nextcloud-vue-collections/tree/vue3
- [x] `@nextcloud/dialogs`: https://github.com/nextcloud-libraries/nextcloud-dialogs/pull/884
- [x] `@nextcloud/upload`: https://github.com/nextcloud-libraries/nextcloud-upload/pull/1197

Other dependencies:

- [x] vue@2 -> vue@3
- [x] vue-router@3 -> vue-router@4
- [x] vuex@3 -> vuex@4
- [x] vuex@4
- [x] vue-cropperjs@4 -> vue-cropperjs@5
- [x] vue-draggable-resizable@2 -> vue-draggable-resizable@3
- [x] vue-observe-visibility@1 -> vue-observe-visibility@2
- [x] `vue-outside-events` - migrate to `vueuse` #12346
- [x] `vue-prevent-unload` - get rid of or migrate to `vueuse` if any #12349
- [x] `vue-shortkey` - check `vue3-shortkey` 
- [x] `vue-virtual-scroller@1` -> `vue-virtual-scroller@2`
- [x] `vue2-leaflet` -> `@vue-leaflet/vue-leaflet`

### 📄 Preparations

Details are to be added to the separated issues.

- [x] Migrate all deprecated in 2.7 things
  - [x] https://github.com/nextcloud/spreed/issues/9449
  - [x] https://github.com/nextcloud/spreed/pull/9410
- [x] Prepare for the migration (with ESLint warnings whenever possible **// todo: create an issue**)
  - [x] [Always use `$scopedSlots` instead of `$slots`](https://v3-migration.vuejs.org/breaking-changes/slots-unification.html)
  - [x] [Do not use Vue component instance as event emitter (EventBus)](https://v3-migration.vuejs.org/breaking-changes/events-api.html), use [mitt](https://github.com/developit/mitt) instead or remove the event bus #11996
  - [x] [Check `v-bind` merge Behavior ](https://v3-migration.vuejs.org/breaking-changes/v-bind.html) #12005
  - [x] https://github.com/nextcloud/spreed/issues/9450 #11993\
- [x] Get rid of global directive registration https://github.com/nextcloud/spreed/pull/12358
- [x] Unify `RoomSelector` mounting https://github.com/nextcloud/spreed/pull/12356

### 🚋 Do the migration

- [x] Create `vue3` branch
- [x] Switch to Vue 3 with minimal running instance:
  - [x] Fix bundling https://github.com/nextcloud/spreed/pull/12352
  - [x] Make the minimal required migration to get app running (bundled successfully), e.g. Vue app init
  - [x] Comment all "optional" failing features, e.g. not migrated libraries
  - [x] Merge to `vue3`
- [ ] Fix all the issues with migration separately uncommenting all the disabled features
  - [x] #12359
  - [x] #12366
  - [x] Return `@nextcloud/uploads`
  - [x] Return `@nextcloud/dialogs`
  - [x] Return `@nextcloud/collections`
  - [ ] Check Leaflet
- [x] #12363
- [x] Fix ESLint using https://github.com/nextcloud-libraries/eslint-config/pull/768
- [x] Add ESLint rules for changed stuff
  - [x] eslintconfig should be aware of vue3 syntax

### Things that are not required for the migration, but would be nice

- Better compatibility with SFC Setup and using new useful features
  - [x] https://github.com/nextcloud/spreed/pull/9457
    - [x] [Define all Vue component events in `emits`](https://v3-migration.vuejs.org/breaking-changes/emits-option.html)
    - [x] [Define all public component methods in `expose`](https://vuejs.org/api/options-state.html#expose)
- Slowly start to follow new Vue recommendations
  - Do not create new mixins. Create composables instead.
  - Do not create new Vuex modules. Create Pinia stores instead.
- [ ] Migrate to Vite (see also https://github.com/nextcloud/spreed/issues/9406)
