### ISSUE TITLE
Release todo 17.0.0-beta.1

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9451]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [ ] Check all milestones don't have priority issues still open
    - [ ] https://github.com/nextcloud/spreed/milestone/176
- [x] On first beta of a major release
    - [x] Create `New in Talk 17` entries in the `Talk updates ✅` conversation
    - [x] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [x] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch

## 🚀 v17.0.0-beta.1
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/9453
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    npm version patch --no-git-tag-version
    ```
   
- [x] Merge the backport
- [x] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable27
    git pull origin stable27
    ```
- [x] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [x] Do a quick smoke test by starting a call with:
    - [x] Chrome
    - [x] Edge
    - [x] Firefox
    - [x] Safari
    - [x] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v17.0.0-beta.1` will be automatically added to the tag)
    ```sh
    make create-tag version=17.0.0-beta.1
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v17.0.0-beta.1
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v17.0.0-beta.1
    - [x] Add the respective `CHANGELOG.md` section
    - [x] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v17.0.0-beta.1
    - [x] Copy the release description from before
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💙 Next Major (27)` to `v17.0.0-beta.1` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💙 Next Beta (27)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v17.0.0-beta.1` to `💜 Next Major (28)`
- [x] Close the `v17.0.0-beta.1` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
