### ISSUE TITLE
Release todo 17.0.0-beta.2

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/spreed#9499]
Get branches/versions to release from https://github.com/nextcloud/spreed/milestones

## 💺 Preparation

- [x] Check there are no pending backports: https://github.com/nextcloud/spreed/labels/backport-request
- [x] Check all milestones don't have priority issues still open
    - [x] https://github.com/nextcloud/spreed/milestone/190
        - [x] https://github.com/nextcloud/spreed/pull/9344
        - [ ] https://github.com/nextcloud/spreed/pull/9460
- [x] On first beta of a major release
    - [ ] Create `New in Talk 17` entries in the `Talk updates ✅` conversation
    - [ ] Create a test package and check if a new development file needs to be added to the packaging exclude list in `Makefile`
    ```sh
    make appstore
    ```
    - [ ] Make sure the GDPR document is updated for new database tables/columns
    - [ ] Make sure dependabot.yml is sending patch updates to the stable branch
- [x] Create a PR against master `CHANGELOG.md` with the changelog of all milestones that are subject to the release
    - [x] https://github.com/nextcloud/spreed/pull/9500
- [x] Merge the PR

## 🚀 v17.0.0-beta.2
Start with the **oldest** version here, so the appstore and github releases show the newest version as "Last release"

- [x] Backport the changelog
    - [x] https://github.com/nextcloud/spreed/pull/9500
    - [x] Remove changelog entries in  `CHANGELOG.md` of higher versions
    - [x] Bump the version in `appinfo/info.xml`
    - [x] Bump the version in `package.json`.  The following command will return a new version name, make sure it matches what you expect:
    ```sh
    # Normal patch releases
    npm version patch --no-git-tag-version

    # First beta releases
    npm version premajor --no-git-tag-version --preid=beta
    npm version prerelease --no-git-tag-version --preid=beta

    # Other beta releases
    npm version prerelease --no-git-tag-version --preid=beta

    # RC releases
    npm version prerelease --no-git-tag-version --preid=rc
    ```
  
   
- [x] Merge the backport
- [ ] Make sure you pull the latest stable branch:
    ```sh
    git checkout stable27
    git pull origin stable27
    ```
- [ ] Clean the dev instance and update all dependencies with the lock file versions and build the production javascript:
    ```sh
    make production-setup
    # On 24 and older versions run:
    # make dev-setup build-js-production
    ```
- [ ] Do a quick smoke test by starting a call with:
    - [ ] Chrome
    - [ ] Edge
    - [ ] Firefox
    - [ ] Safari
    - [ ] Desktop client (Talk 16+)
    - [ ] Android app
    - [ ] iOS app
- [x] Create tag (note that the leading `v` in `v17.0.0-beta.2` will be automatically added to the tag)
    ```sh
    make create-tag version=17.0.0-beta.2
    ```
- [x] Push the git tag to https://github.com/nextcloud-releases/spreed
    ```sh
    git push releases v17.0.0-beta.2
    ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud/spreed/releases/new?tag=v17.0.0-beta.2
    - [x] Add the respective `CHANGELOG.md` section
    - [x] Use the **Generate release notes** button and wrap put the result into
        ```
        ## What's Changed
        
        <details>
        
        </details>
        ```
- [x] Mark the tag as a (pre-)release in https://github.com/nextcloud-releases/spreed/releases/new?tag=v17.0.0-beta.2
    - [x] Copy the release description from before
- [x] Check that the GitHub Action started: https://github.com/nextcloud-releases/spreed/actions
- [x] Rename milestone `💙 Next Beta (27)` to `v17.0.0-beta.2` in https://github.com/nextcloud/spreed/milestones
    Unless last release of the stable branch:
    - [x] Create a follow up milestone for `💙 Next Beta (27)` (Due date in ~4 weeks, ~4 days for beta/RC)
    - [x] Move all open PRs and issues from milestone `v17.0.0-beta.2` to `💙 Next Beta (27)`
- [x] Close the `v17.0.0-beta.2` milestone
- [x] Ensure that the GitHub Action finished successfully: https://github.com/nextcloud-releases/spreed/actions
- [x] In case there were security issues fixed ping the security team
